remote_theme: just-the-docs/just-the-docs

title: ZZZK's Capstone Design
description: A Jekyll theme for documentation
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://inu-capstone-project-zzzk.github.io" # the base hostname & protocol for your site, e.g. http://example.com
repository: INU-Capstone-Project-ZZZK/inu-capstone-project-zzzk.github.io # for github-metadata
