remote_theme: just-the-docs/just-the-docs

title: ZZZK's Capstone Design
description: A Jekyll theme for documentation
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://inu-capstone-project-zzzk.github.io" # the base hostname & protocol for your site, e.g. http://example.com
repository: INU-Capstone-Project-ZZZK/inu-capstone-project-zzzk.github.io # for github-metadata

# Footer "Edit this page on GitHub" link text
gh_edit_link: true # show or hide edit this page link
gh_edit_link_text: "Edit this page on GitHub"
gh_edit_repository: "https://github.com/INU-Capstone-Project-ZZZK/inu-capstone-project-zzzk.github.io.git" # the github URL for your repo
gh_edit_branch: "main" # the branch that your docs is served from
# gh_edit_source: docs # the source that your files originate from
gh_edit_view_mode: "tree" # "tree" or "edit" if you want the user to jump into the editor immediately
